#pragma once

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 800
#define PLAYER_SPEED 20.0f
#define PLAYER_ANGULAR_SPEED 360
#define ANGULAR_FRICTION  200
#define ENEMY_COUNT 14
#define BULLET_CAPACITY 20
#define MAX_ENEMY_LIFE 3
